//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingilizcekonusmaogrenmeuygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kursiyerler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kursiyerler()
        {
            this.Egitmenlers = new HashSet<Egitmenler>();
        }
    
        public int KursiyerNo { get; set; }
        public string KursiyerAdSoyad { get; set; }
        public string KursiyerTelefon { get; set; }
        public string KursiyerAdres { get; set; }
        public string KursiyerDilSeviyesi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egitmenler> Egitmenlers { get; set; }
    }
}
