//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingilizcekonusmaogrenmeuygulamasi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class İngilizceKonusmaOgrenmeUygulamasiEntities : DbContext
    {
        public İngilizceKonusmaOgrenmeUygulamasiEntities()
            : base("name=İngilizceKonusmaOgrenmeUygulamasiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egitmenler> Egitmenlers { get; set; }
        public virtual DbSet<Konular> Konulars { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Kursiyerler> Kursiyerlers { get; set; }
    }
}
